-- MySQL Script generated by MySQL Workbench
-- Thu Jul 24 14:27:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema franck
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `franck` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `franck` ;

-- -----------------------------------------------------
-- Table `franck`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `franck`.`task` ;

CREATE TABLE IF NOT EXISTS `franck`.`task` (
  `idtask` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(10000) NULL DEFAULT NULL,
  `is_done` TINYINT NOT NULL,
  `moment` ENUM('avant', 'pendant', 'aprés') NOT NULL,
  `game_id` INT NULL,
  PRIMARY KEY (`idtask`),
  UNIQUE INDEX `idtask_UNIQUE` (`idtask` ASC) VISIBLE,
  INDEX `fk_task_game_idx` (`game_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `franck`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `franck`.`game` ;

CREATE TABLE IF NOT EXISTS `franck`.`game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `main_objective_1` VARCHAR(100) NULL DEFAULT NULL,
  `main_objective_2` VARCHAR(100) NULL DEFAULT NULL,
  `main_objective_3` VARCHAR(100) NULL DEFAULT NULL,
  `age_of_audience` INT NOT NULL,
  `duration` INT NOT NULL,
  `number_of_players` INT NOT NULL,
  `type_of` VARCHAR(45) NOT NULL,
  `moment_of_day` VARCHAR(45) NULL DEFAULT NULL,
  `place` VARCHAR(45) NOT NULL,
  `no_material` VARCHAR(500) NOT NULL,
  `art_material` VARCHAR(500) NOT NULL,
  `sport_material` VARCHAR(500) NOT NULL,
  `other_material` VARCHAR(500) NOT NULL,
  `rules` TEXT NULL DEFAULT NULL,
  `variant` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idGame_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `franck`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `franck`.`user` ;

CREATE TABLE IF NOT EXISTS `franck`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `franck`.`prepared_game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `franck`.`prepared_game` ;

CREATE TABLE IF NOT EXISTS `franck`.`prepared_game` (
  `game_id` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`game_id`, `user_iduser`),
  INDEX `fk_game_has_user_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_prepared_game_game_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_prepared_game_game`
    FOREIGN KEY (`game_id`)
    REFERENCES `franck`.`game` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_game_has_user_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `franck`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Adding foreign key constraints
-- -----------------------------------------------------
ALTER TABLE `franck`.`task` 
ADD CONSTRAINT `fk_task_game`
  FOREIGN KEY (`game_id`)
  REFERENCES `franck`.`game` (`id`)
  ON DELETE SET NULL
  ON UPDATE CASCADE;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
